### ISSUE TITLE
12hr format missing in live rader

### ISSUE THREAD

**Issue by freyjasasi** [PranshulGG/WeatherMaster#76] opened 2024-10-17 10:21 UTC
In live rader, it has 24-hour format even though in settings it is set to 12hr

**Comment by PranshulGG** [comment] 2024-10-17 10:34
I’m not sure, but I checked and it worked fine. Maybe try setting it to 24-hour format and then back to 12-hour. It might be an issue with the saved value.

![Screenshot_20241017-160232.png](https://github.com/user-attachments/assets/cf822862-e8b6-49a8-811a-8186a250c42f)

**Comment by PranshulGG** [comment] 2024-10-17 16:00
> It's not working. I tried switching and restarting app but no use. Still, it's in 24-hour format only.

Is this issue only with the radar, or does it affect the whole app? Maybe try clearing the app data.

**Comment by freyjasasi** [comment] 2024-10-17 16:03
The rest of the app is fine. I tried clearing cache, too, after changing the time format

**Comment by PranshulGG** [comment] 2024-10-17 16:06
> The rest of the app is fine. I tried clearing cache, too, after changing the time format

Did you tried clearing the app data?

**Comment by freyjasasi** [comment] 2024-10-17 16:08
I did a fresh install

**Comment by PranshulGG** [comment] 2024-10-17 16:11
> I did a fresh install of v1.6.7

Yeah, but it doesn’t clear your app data. I don’t know how to reproduce the issue. It’s working fine on my end, and the code seems to be fine too.

**Comment by freyjasasi** [comment] 2024-10-17 16:15
Hmm OK. I will check once

**Comment by PranshulGG** [comment] 2024-10-17 17:00
@freyjasasi Close the issue if its solved.

**Closed** 2024-10-18 14:44 UTC
Labels: question
