### ISSUE TITLE
Izzyondroid version not up to date

### ISSUE THREAD

**Issue by Quiwy** [PranshulGG/WeatherMaster#61] opened 2024-10-07 11:52 UTC
Hi,

The izzyondroid repo is not up-to-date with the last GitHub version.

Is there anything you can do to publish it, or do we just have to wait ?

Thank you for your help !

**Comment by IzzySoft** [comment] 2024-10-07 13:34
No, "just waiting" won't fix it: you've changed the signing key, @PranshulGG:

```
2024-10-06 19:44:24,129 WARNING: "com.example.weathermaster_56.apk" is signed by a key that is not allowed:
e68cd7cddf7bb76071e38bdfc3268bfa454367a1eb777be02634df182c16ad46
```

Previous release used this one:

```
Signer #1 certificate DN: CN=weather
Signer #1 certificate SHA-256 digest: c97f592ad5a426ef17aa4b113aa8f9c1bc3c2f2675c857ad86bdacc05fbeee01
Signer #1 certificate SHA-1 digest: 3dba6155dca56bf75a3b5f07171f14e5120272d3
Signer #1 certificate MD5 digest: 8a17a9f878d3953956cb9c6e5fc25ac6
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

Now you are using this:

```
Signer #1 certificate DN: CN=pranshul
Signer #1 certificate SHA-256 digest: e68cd7cddf7bb76071e38bdfc3268bfa454367a1eb777be02634df182c16ad46
Signer #1 certificate SHA-1 digest: fa7310a540c45a3734c3292fecd0975be394328c
Signer #1 certificate MD5 digest: dbca7c49aff01c84658d0382b6dc8bf1
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

You see the SHA-256 digest does not match, so the new APK was rejected for security reasons. What happened to your original signing key? Until we've solved this, there won't be any updates at IoD. For some background, see e.g. [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss)

**Comment by PranshulGG** [comment] 2024-10-07 13:37
I recoded the whole app because it was having issues generating the APK for some reason.

**Comment by IzzySoft** [comment] 2024-10-07 14:31
Do you still have access to your original keystore/signing key? A changed signing key also means those having the previous version installed cannot update without uninstalling the app first, as you probably know. If the original keystore is lost, we have a bigger problem here: how can one be sure it's really you – and not someone having taken over your account (see the article linked above). Even if you completely rewrote the app, you can still use the very same keystore/signing-key, and in this case even should.

**Comment by PranshulGG** [comment] 2024-10-07 14:45
Yes, I still have access to the original keystore and signing key.

**Comment by IzzySoft** [comment] 2024-10-08 07:12
Great! That helps a lot. It basically gives us 2 options:

* the recommended one: keep using that original keystore and signing key. This would also allow seamless updates from previous versions.
* switch to the new key. This requires a bit more effort. You could either use [Signing Key Rotation](https://anandbose.dev/2020/05/08/android-signing-key-rotation-explained/) (for seamless updates on Android 9+) – or provide a copy of the exact same APK attached to the latest release now but signed with the original key, for verification, so we allow the new signing key here (and disable the old one after a given overlap). Without key rotation, this of course means no seamless updates but uninstall/reinstall.

Which approach will you take? I'd then help you with the next steps if I can.

**Comment by PranshulGG** [comment] 2024-10-08 07:23
I’ve decided to go with the first option. Should I proceed by releasing the new version using the original keystore?

**Comment by IzzySoft** [comment] 2024-10-08 07:54
Yes, that would work perfectly. Just let me know once it's available, so I can re-enable auto updates here (which were paused to to the conflict).

You might also want to add a comment to the release made with the different key, so nobody taps into a trap with it by accident (though one of course should pick the latest release anyway).

**Comment by PranshulGG** [comment] 2024-10-08 08:03
Yep, that sounds good!

**Comment by IzzySoft** [comment] 2024-10-08 10:09
Worked out fine, thanks! Update should roll out with the next sync around 6 pm UTC today. So once @Quiwy confirmed (please do a (pull-to-)refresh in your F-Droid client to make sure the index is updated and report back here), I guess this issue can be closed :smiley:

Thanks for your swift action, @PranshulGG!

**Closed** 2024-10-08 10:11 UTC

**Comment by Quiwy** [comment] 2024-10-08 18:40
I confirm I had the update. Thank you very much both of you for your help !

**Comment by PranshulGG** [comment] 2024-10-24 15:54
@IzzySoft Hey, I hope you're doing well! I just wanted to ask if it's possible to update the screenshot of WeatherMaster on IzzyOnDroid?

**Comment by IzzySoft** [comment] 2024-10-24 22:45
Sure it is! May I counter that with a suggestion? Mind to set up Fastlane structures here in your repo (I could send you what we've set up for you at IzzyOnDroid as a starter package, and you could then use the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) to build on that)? Once done, you let me know and I'll enable it on our end, plus manually trigger an initial pull. From then on, with each release pulled into IzzyOnDroid, your Fastlane structures would be checked as well and changes be pulled along ­so you'd be in control of how your app is presented, and can make sure description/screenshots match the latest release. Deal?

**Comment by PranshulGG** [comment] 2024-10-25 02:38
@IzzySoft Yep, sounds good

**Comment by IzzySoft** [comment] 2024-10-25 12:26
Cool! Then I wait for your ping here when it's ready?

**Comment by PranshulGG** [comment] 2024-10-25 12:30
@IzzySoft Yes, I'd like to take the starter package to set up Fastlane in my repo. Once I have it configured, I'll ping you to let you know it's ready.

**Comment by IzzySoft** [comment] 2024-10-25 12:32
OK, there you go then :smiley:

**Comment by PranshulGG** [comment] 2024-10-25 12:35
I’ll go through the documentation and set it up in my repo. If I have any questions, I’ll reach out. Thanks!

**Comment by PranshulGG** [comment] 2024-10-25 13:06
@IzzySoft When I release a new tag, are the changes I made in the fastlane/metadata/android/en-US automatically applied to the IzzyOnDroid repository, or do I need to ensure that the latest changes are synced?

**Comment by IzzySoft** [comment] 2024-10-25 23:07
> are the changes I made in the fastlane/metadata/android/en-US automatically applied to the IzzyOnDroid repository

Fastlane is checked and differences are synced whenever a new release was detected and pulled.

> can I add the screenshots used in the README file of the WeatherMaster GitHub repo? 

You can replace the screenshots from my PR with those, and then adjust the links in your Readme. Note that symbolic links are not supported (due to limitations of the Github API).

> Additionally, is there a process to follow if I decide to change the package name of my app?

Changing the packageName makes it another app, as that's the unique identifier of your application. Whoever had a previous version installed, needs to perform a fresh install. There will be no update notifications for that, as no update is possible. So the process would be the one of establishing a new app.
