### ISSUE TITLE
The selected language is always displayed as English in the settings page

### ISSUE THREAD

**Issue by Tuan1-2-3** [PranshulGG/WeatherMaster#150] opened 2024-11-23 12:49 UTC
### Describe your issue

Although French is the selected language, the settings page still displays it in English.

### Steps to reproduce

1. Go to 'Setting'
2. Swipe down to 'App Language'
3. See the issue

### Put here any screenshots or videos (optional)

![IMG_20241123_193728](https://github.com/user-attachments/assets/b34a1ac9-3d68-4571-9fe1-ce3f1f54a25a)

**Comment by PranshulGG** [comment] 2024-11-23 12:50
Not a bug, just open the settings page again after closing

**Closed by PranshulGG** 2024-11-23 12:50 UTC
Labels: wontfix
