### ISSUE TITLE
cant add my own apis

### ISSUE THREAD

**Issue by Joeeeeb5** [PranshulGG/WeatherMaster#67] opened 2024-10-09 04:20 UTC
i tried both accu and owm but none of them work

**Comment by Joeeeeb5** [comment] 2024-10-09 04:21
openweather started working by itself, accuweather still unusable

**Comment by PranshulGG** [comment] 2024-10-09 04:32
Yep, it’s a bug. The issue is already tracked, so I’ll close this since it’s a duplicate.

**Closed** 2024-10-09 04:32 UTC
Labels: duplicate
